import type { ProductType } from "@/types";

const now = "2026-05-20T00:00:00.000Z";

const teeCategory = { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" };
const hoodieCategory = { id: 2, name: "Hoodies", description: "RESEY Hoodies" };
const pantsCategory = { id: 3, name: "Pants", description: "RESEY Pants" };
const accessoriesCategory = {
  id: 4,
  name: "Accessories",
  description: "RESEY Accessories",
};

export const sampleProducts: ProductType[] = [
  {
    product_id: "resey-washed-tee-brown",
    slug: "resey-washed-tee-brown",
    title: "RESEY Washed Tee - Brown",
    description:
      "Áo thun wash màu nâu, form boxy rộng, logo chìm và đường ráp lệch tạo điểm nhấn streetwear.",
    material: "Washed cotton 250gsm",
    price: 590000,
    image: "/products/resey-washed-tee-brown-fit-02.jpg",
    stock: 36,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Dust Brown", "Olive"],
    is_active: true,
    sku: "RS-TEE-101",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-brown-crop-fit",
    slug: "resey-washed-tee-brown-crop-fit",
    title: "RESEY Brown Washed Crop Fit",
    description:
      "Phiên bản fit ngắn hơn cho outfit layer, chất cotton wash mềm và màu nâu vintage dễ phối.",
    material: "Washed cotton 240gsm",
    price: 560000,
    image: "/products/resey-washed-tee-brown-fit-03.jpg",
    stock: 28,
    sizes: ["S", "M", "L"],
    colors: ["Brown", "Dust Brown"],
    is_active: true,
    sku: "RS-TEE-102",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-olive",
    slug: "resey-washed-tee-olive",
    title: "RESEY Washed Tee - Olive",
    description:
      "Áo thun wash màu olive xám, form rộng, hợp phối với quần trắng, denim hoặc cargo.",
    material: "Washed cotton 250gsm",
    price: 590000,
    image: "/products/resey-washed-tee-olive-fit-01.jpg",
    stock: 32,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Dust Gray", "Brown"],
    is_active: true,
    sku: "RS-TEE-103",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-street-set",
    slug: "resey-washed-tee-street-set",
    title: "RESEY Washed Tee Street Set",
    description:
      "Set phối áo wash nâu cùng quần ống rộng, phù hợp lookbook và outfit đường phố hằng ngày.",
    material: "Washed cotton tee / cotton twill pants",
    price: 1190000,
    image: "/products/resey-washed-tee-brown-fit-01.jpg",
    stock: 16,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Cream"],
    is_active: true,
    sku: "RS-SET-104",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-wide-leg-cream-pants",
    slug: "resey-wide-leg-cream-pants",
    title: "RESEY Wide Leg Pants - Cream",
    description:
      "Quần ống rộng màu cream, dáng rũ, dễ phối với các dòng tee wash của RESEY.",
    material: "Cotton twill",
    price: 760000,
    image: "/products/resey-washed-tee-brown-fit-05.jpg",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "White"],
    is_active: true,
    sku: "RS-PAN-105",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-wide-leg-dust-pants",
    slug: "resey-wide-leg-dust-pants",
    title: "RESEY Wide Leg Pants - Dust Gray",
    description:
      "Quần ống rộng wash bụi, dáng streetwear mạnh, phối tốt với áo nâu hoặc olive.",
    material: "Washed cotton twill",
    price: 790000,
    image: "/products/resey-washed-tee-brown-fit-04.jpg",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dust Gray", "Brown"],
    is_active: true,
    sku: "RS-PAN-106",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-oversized-tee",
    slug: "resey-oversized-tee",
    title: "RESEY Oversized Tee",
    description: "Áo thun form rộng cho streetwear hằng ngày.",
    material: "Cotton 240gsm",
    price: 450000,
    image: "/products/resey-washed-tee-brown-fit-02.jpg",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-001",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-minimal-hoodie",
    slug: "resey-minimal-hoodie",
    title: "RESEY Minimal Hoodie",
    description: "Hoodie nỉ dày, tối giản, giữ form tốt.",
    material: "French terry cotton blend",
    price: 790000,
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
    stock: 24,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-002",
    category_id: 2,
    category: hoodieCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-street-cargo-pants",
    slug: "resey-street-cargo-pants",
    title: "RESEY Street Cargo Pants",
    description: "Cargo pants utility fit, thoải mái khi di chuyển.",
    material: "Cotton twill",
    price: 920000,
    image: "/products/resey-washed-tee-brown-fit-04.jpg",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Dust Gray"],
    is_active: true,
    sku: "SL-PAN-003",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-logo-cap",
    slug: "resey-logo-cap",
    title: "RESEY Logo Cap",
    description: "Nón lưỡi trai basic tone đen/trắng.",
    material: "Cotton canvas",
    price: 320000,
    image:
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
    stock: 60,
    sizes: ["Free Size"],
    colors: ["Black", "White", "Beige"],
    is_active: true,
    sku: "SL-ACC-004",
    category_id: 4,
    category: accessoriesCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-heavyweight-tee",
    slug: "resey-heavyweight-tee",
    title: "RESEY Heavyweight Tee",
    description: "Áo thun heavy cotton, chất dày, đứng form.",
    material: "Heavyweight cotton 260gsm",
    price: 520000,
    image: "/products/resey-washed-tee-brown-fit-03.jpg",
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-005",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-dragon-graphic-tee",
    slug: "resey-dragon-graphic-tee",
    title: "RESEY Dragon Graphic Tee",
    description: "Graphic tee phiên bản giới hạn.",
    material: "Cotton jersey",
    price: 680000,
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    stock: 12,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-006",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-boxy-tee",
    slug: "resey-boxy-tee",
    title: "RESEY Boxy Tee",
    description: "Boxy tee với form rộng, gọn và dễ phối đồ.",
    material: "Compact cotton",
    price: 560000,
    image: "/products/resey-washed-tee-brown-fit-01.jpg",
    stock: 22,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-007",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-club-hoodie",
    slug: "resey-club-hoodie",
    title: "RESEY Club Hoodie",
    description: "Hoodie signature của RESEY.",
    material: "Brushed fleece",
    price: 850000,
    image:
      "https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=900&q=80",
    stock: 14,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-008",
    category_id: 2,
    category: hoodieCategory,
    created_at: now,
    updated_at: now,
  },
];

export function mergeWithSampleProducts(products: ProductType[]): ProductType[] {
  const existingSkus = new Set(products.map((product) => product.sku).filter(Boolean));
  const existingIds = new Set(products.map((product) => product.product_id));
  const missingSamples = sampleProducts.filter(
    (product) =>
      !(product.sku && existingSkus.has(product.sku)) &&
      !existingIds.has(product.product_id),
  );

  return [...products, ...missingSamples];
}

export function findSampleProduct(identifier: string): ProductType | null {
  return (
    sampleProducts.find(
      (product) =>
        product.slug === identifier ||
        product.product_id === identifier ||
        product.sku === identifier,
    ) || null
  );
}
