import type { ProductType } from "@/types";

const now = "2026-05-20T00:00:00.000Z";

export const sampleProducts: ProductType[] = [
  {
    product_id: "resey-oversized-tee",
    slug: "resey-oversized-tee",
    title: "RESEY Oversized Tee",
    description: "Áo thun form rộng cho streetwear hằng ngày.",
    material: "Cotton 240gsm",
    price: 450000,
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-001",
    category_id: 1,
    category: { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-minimal-hoodie",
    slug: "resey-minimal-hoodie",
    title: "RESEY Minimal Hoodie",
    description: "Hoodie nỉ dày, tối giản, giữ form tốt.",
    material: "French terry cotton blend",
    price: 790000,
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
    stock: 24,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-002",
    category_id: 2,
    category: { id: 2, name: "Hoodies", description: "RESEY Hoodies" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-street-cargo-pants",
    slug: "resey-street-cargo-pants",
    title: "RESEY Street Cargo Pants",
    description: "Cargo pants utility fit, thoải mái khi di chuyển.",
    material: "Cotton twill",
    price: 920000,
    image:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-PAN-003",
    category_id: 3,
    category: { id: 3, name: "Pants", description: "RESEY Pants" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-logo-cap",
    slug: "resey-logo-cap",
    title: "RESEY Logo Cap",
    description: "Nón lưỡi trai basic tone đen/trắng.",
    material: "Cotton canvas",
    price: 320000,
    image:
      "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
    stock: 60,
    sizes: ["Free Size"],
    colors: ["Black", "White", "Beige"],
    is_active: true,
    sku: "SL-ACC-004",
    category_id: 4,
    category: { id: 4, name: "Accessories", description: "RESEY Accessories" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-heavyweight-tee",
    slug: "resey-heavyweight-tee",
    title: "RESEY Heavyweight Tee",
    description: "Áo thun heavy cotton, chất dày, đứng form.",
    material: "Heavyweight cotton 260gsm",
    price: 520000,
    image:
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=900&q=80",
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-005",
    category_id: 1,
    category: { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-dragon-graphic-tee",
    slug: "resey-dragon-graphic-tee",
    title: "RESEY Dragon Graphic Tee",
    description: "Graphic tee phiên bản giới hạn.",
    material: "Cotton jersey",
    price: 680000,
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    stock: 12,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-006",
    category_id: 1,
    category: { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-boxy-tee",
    slug: "resey-boxy-tee",
    title: "RESEY Boxy Tee",
    description: "Boxy tee với form rộng, gọn và dễ phối đồ.",
    material: "Compact cotton",
    price: 560000,
    image:
      "https://images.unsplash.com/photo-1506629905607-d405b7a30db9?auto=format&fit=crop&w=900&q=80",
    stock: 22,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-007",
    category_id: 1,
    category: { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" },
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-club-hoodie",
    slug: "resey-club-hoodie",
    title: "RESEY Club Hoodie",
    description: "Hoodie signature của RESEY.",
    material: "Brushed fleece",
    price: 850000,
    image:
      "https://images.unsplash.com/photo-1578681994506-b8f463449011?auto=format&fit=crop&w=900&q=80",
    stock: 14,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-008",
    category_id: 2,
    category: { id: 2, name: "Hoodies", description: "RESEY Hoodies" },
    created_at: now,
    updated_at: now,
  },
];

export function findSampleProduct(identifier: string): ProductType | null {
  return (
    sampleProducts.find(
      (product) =>
        product.slug === identifier || product.product_id === identifier,
    ) || null
  );
}
