import type { ProductType } from "@/types";

const now = "2026-05-20T00:00:00.000Z";

const teeCategory = { id: 1, name: "T-Shirts", description: "RESEY T-Shirts" };
const hoodieCategory = { id: 2, name: "Hoodies", description: "RESEY Hoodies" };
const pantsCategory = { id: 3, name: "Pants", description: "RESEY Pants" };
const accessoriesCategory = {
  id: 4,
  name: "Accessories",
  description: "RESEY Accessories",
};

export const sampleProducts: ProductType[] = [
  {
    product_id: "resey-washed-tee-brown",
    slug: "resey-washed-tee-brown",
    title: "RESEY Washed Tee - Brown",
    description:
      "ﾃ｛ thun wash mﾃu nﾃ｢u, form boxy r盻冢g, logo chﾃｬm vﾃ ﾄ柁ｰ盻拵g rﾃ｡p l盻㌘h t蘯｡o ﾄ訴盻ノ nh蘯･n streetwear.",
    material: "Washed cotton 250gsm",
    price: 590000,
    image: "/products/resey-washed-tee-brown-fit-02.jpg",
    stock: 36,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Dust Brown", "Olive"],
    is_active: true,
    sku: "RS-TEE-101",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-brown-crop-fit",
    slug: "resey-washed-tee-brown-crop-fit",
    title: "RESEY Brown Washed Crop Fit",
    description:
      "Phiﾃｪn b蘯｣n fit ng蘯ｯn hﾆ｡n cho outfit layer, ch蘯･t cotton wash m盻［ vﾃ mﾃu nﾃ｢u vintage d盻・ph盻訴.",
    material: "Washed cotton 240gsm",
    price: 560000,
    image: "/products/resey-washed-tee-brown-fit-03.jpg",
    stock: 28,
    sizes: ["S", "M", "L"],
    colors: ["Brown", "Dust Brown"],
    is_active: true,
    sku: "RS-TEE-102",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-olive",
    slug: "resey-washed-tee-olive",
    title: "RESEY Washed Tee - Olive",
    description:
      "ﾃ｛ thun wash mﾃu olive xﾃ｡m, form r盻冢g, h盻｣p ph盻訴 v盻嬖 qu蘯ｧn tr蘯ｯng, denim ho蘯ｷc cargo.",
    material: "Washed cotton 250gsm",
    price: 590000,
    image: "/products/resey-washed-tee-olive-fit-01.jpg",
    stock: 32,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Olive", "Dust Gray", "Brown"],
    is_active: true,
    sku: "RS-TEE-103",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-washed-tee-street-set",
    slug: "resey-washed-tee-street-set",
    title: "RESEY Washed Tee Street Set",
    description:
      "Set ph盻訴 ﾃ｡o wash nﾃ｢u cﾃｹng qu蘯ｧn 盻創g r盻冢g, phﾃｹ h盻｣p lookbook vﾃ outfit ﾄ柁ｰ盻拵g ph盻・h蘯ｱng ngﾃy.",
    material: "Washed cotton tee / cotton twill pants",
    price: 1190000,
    image: "/products/resey-washed-tee-brown-fit-01.jpg",
    stock: 16,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Brown", "Cream"],
    is_active: true,
    sku: "RS-SET-104",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-wide-leg-cream-pants",
    slug: "resey-wide-leg-cream-pants",
    title: "RESEY Wide Leg Pants - Cream",
    description:
      "Qu蘯ｧn 盻創g r盻冢g mﾃu cream, dﾃ｡ng rﾅｩ, d盻・ph盻訴 v盻嬖 cﾃ｡c dﾃｲng tee wash c盻ｧa RESEY.",
    material: "Cotton twill",
    price: 760000,
    image: "/products/resey-washed-tee-brown-fit-05.jpg",
    stock: 20,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Cream", "White"],
    is_active: true,
    sku: "RS-PAN-105",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-wide-leg-dust-pants",
    slug: "resey-wide-leg-dust-pants",
    title: "RESEY Wide Leg Pants - Dust Gray",
    description:
      "Qu蘯ｧn 盻創g r盻冢g wash b盻･i, dﾃ｡ng streetwear m蘯｡nh, ph盻訴 t盻奏 v盻嬖 ﾃ｡o nﾃ｢u ho蘯ｷc olive.",
    material: "Washed cotton twill",
    price: 790000,
    image: "/products/resey-washed-tee-brown-fit-04.jpg",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dust Gray", "Brown"],
    is_active: true,
    sku: "RS-PAN-106",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-oversized-tee",
    slug: "resey-oversized-tee",
    title: "RESEY Oversized Tee",
    description: "ﾃ｛ thun form r盻冢g cho streetwear h蘯ｱng ngﾃy.",
    material: "Cotton 240gsm",
    price: 450000,
    image: "/products/resey-washed-tee-brown-fit-02.jpg",
    stock: 40,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-001",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-minimal-hoodie",
    slug: "resey-minimal-hoodie",
    title: "RESEY Minimal Hoodie",
    description: "Hoodie n盻・dﾃy, t盻訴 gi蘯｣n, gi盻ｯ form t盻奏.",
    material: "French terry cotton blend",
    price: 790000,
    image:
      "/images/products/black-tee-fallback.jpg",
    stock: 24,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-002",
    category_id: 2,
    category: hoodieCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-street-cargo-pants",
    slug: "resey-street-cargo-pants",
    title: "RESEY Street Cargo Pants",
    description: "Cargo pants utility fit, tho蘯｣i mﾃ｡i khi di chuy盻ハ.",
    material: "Cotton twill",
    price: 920000,
    image: "/products/resey-washed-tee-brown-fit-04.jpg",
    stock: 18,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Dust Gray"],
    is_active: true,
    sku: "SL-PAN-003",
    category_id: 3,
    category: pantsCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-logo-cap",
    slug: "resey-logo-cap",
    title: "RESEY Logo Cap",
    description: "Nﾃｳn lﾆｰ盻｡i trai basic tone ﾄ粗n/tr蘯ｯng.",
    material: "Cotton canvas",
    price: 320000,
    image:
      "/images/products/black-tee-fallback.jpg",
    stock: 60,
    sizes: ["Free Size"],
    colors: ["Black", "White", "Beige"],
    is_active: true,
    sku: "SL-ACC-004",
    category_id: 4,
    category: accessoriesCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-heavyweight-tee",
    slug: "resey-heavyweight-tee",
    title: "RESEY Heavyweight Tee",
    description: "ﾃ｛ thun heavy cotton, ch蘯･t dﾃy, ﾄ黛ｻｩng form.",
    material: "Heavyweight cotton 260gsm",
    price: 520000,
    image: "/products/resey-washed-tee-brown-fit-03.jpg",
    stock: 30,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-005",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-dragon-graphic-tee",
    slug: "resey-dragon-graphic-tee",
    title: "RESEY Dragon Graphic Tee",
    description: "Graphic tee phiﾃｪn b蘯｣n gi盻嬖 h蘯｡n.",
    material: "Cotton jersey",
    price: 680000,
    image:
      "/images/products/black-tee-fallback.jpg",
    stock: 12,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-TEE-006",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-boxy-tee",
    slug: "resey-boxy-tee",
    title: "RESEY Boxy Tee",
    description: "Boxy tee v盻嬖 form r盻冢g, g盻肱 vﾃ d盻・ph盻訴 ﾄ黛ｻ・",
    material: "Compact cotton",
    price: 560000,
    image: "/products/resey-washed-tee-brown-fit-01.jpg",
    stock: 22,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray", "Brown"],
    is_active: true,
    sku: "SL-TEE-007",
    category_id: 1,
    category: teeCategory,
    created_at: now,
    updated_at: now,
  },
  {
    product_id: "resey-club-hoodie",
    slug: "resey-club-hoodie",
    title: "RESEY Club Hoodie",
    description: "Hoodie signature c盻ｧa RESEY.",
    material: "Brushed fleece",
    price: 850000,
    image:
      "/images/products/black-tee-fallback.jpg",
    stock: 14,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Gray"],
    is_active: true,
    sku: "SL-HOO-008",
    category_id: 2,
    category: hoodieCategory,
    created_at: now,
    updated_at: now,
  },
];

export function mergeWithSampleProducts(products: ProductType[]): ProductType[] {
  const existingSkus = new Set(products.map((product) => product.sku).filter(Boolean));
  const existingIds = new Set(products.map((product) => product.product_id));
  const missingSamples = sampleProducts.filter(
    (product) =>
      !(product.sku && existingSkus.has(product.sku)) &&
      !existingIds.has(product.product_id),
  );

  return [...products, ...missingSamples];
}

export function findSampleProduct(identifier: string): ProductType | null {
  return (
    sampleProducts.find(
      (product) =>
        product.slug === identifier ||
        product.product_id === identifier ||
        product.sku === identifier,
    ) || null
  );
}

